//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewChatSednev
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContatsUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContatsUser()
        {
            this.ContactMessage = new HashSet<ContactMessage>();
        }
    
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdFriend { get; set; }
        public int Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactMessage> ContactMessage { get; set; }
        public virtual UserData UserData { get; set; }
    }
}
